AWSTemplateFormatVersion: '2010-09-09'
Description: Pipeline with CodeDeploy and AppConfig

Resources:
  # S3 Bucket for CodePipeline artifacts
  PipelineBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'my-pipeline-artifacts-bucket'

  # CodeCommit Repository
  CodeCommitRepository:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: 'MyAppRepository'
      RepositoryDescription: 'Repository for MyApp'

  # IAM Role for CodePipeline
  CodePipelineServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codepipeline.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'CodePipelinePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:*'
                  - 'codebuild:*'
                  - 'codedeploy:*'
                  - 'appconfig:*'
                Resource: '*'

  # IAM Role for CodeBuild
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codebuild.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'CodeBuildPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:*'
                  - 'codecommit:*'
                Resource: '*'

  # CodeBuild Project
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: 'MyAppBuildProject'
      Source:
        Type: 'CODECOMMIT'
        Location: !GetAtt CodeCommitRepository.CloneUrlHttp
      Artifacts:
        Type: 'S3'
        Location: !Ref PipelineBucket
      Environment:
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: 'aws/codebuild/standard:4.0'
        Type: 'LINUX_CONTAINER'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn

  # CodeDeploy Application
  CodeDeployApplication:
    Type: 'AWS::CodeDeploy::Application'
    Properties:
      ApplicationName: 'MyAppDeployApplication'

  # CodeDeploy Deployment Group
  CodeDeployDeploymentGroup:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: 'MyAppDeploymentGroup'
      ServiceRoleArn: !GetAtt CodePipelineServiceRole.Arn
      DeploymentConfigName: 'CodeDeployDefault.AllAtOnce'
      Ec2TagFilters:
        - Key: 'Name'
          Value: 'MyAppInstance'
          Type: 'KEY_AND_VALUE'

  # CodePipeline
  MyCodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: 'S3'
        Location: !Ref PipelineBucket
      Stages:
        - Name: 'Source'
          Actions:
            - Name: 'Source'
              ActionTypeId:
                Category: 'Source'
                Owner: 'AWS'
                Provider: 'CodeCommit'
                Version: '1'
              OutputArtifacts:
                - Name: 'SourceOutput'
              Configuration:
                RepositoryName: !Ref CodeCommitRepository
                BranchName: 'main'
        - Name: 'Build'
          Actions:
            - Name: 'Build'
              ActionTypeId:
                Category: 'Build'
                Owner: 'AWS'
                Provider: 'CodeBuild'
                Version: '1'
              InputArtifacts:
                - Name: 'SourceOutput'
              OutputArtifacts:
                - Name: 'BuildOutput'
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: 'Deploy'
          Actions:
            - Name: 'Deploy'
              ActionTypeId:
                Category: 'Deploy'
                Owner: 'AWS'
                Provider: 'CodeDeploy'
                Version: '1'
              InputArtifacts:
                - Name: 'BuildOutput'
              Configuration:
                ApplicationName: !Ref CodeDeployApplication
                DeploymentGroupName: !Ref CodeDeployDeploymentGroup
